### PR TITLE
Save file to output stream instead of local directory

### LINKED ISSUE #26: NoSuchFileException for live webapp
Kevin Workman - SPS Team
35 mins

Here's the error I found in the logs:
```
Docx4JException: Exception creating output stream: /base/data/home/apps/s~summer20-sps-33/1.428279164077621960/Getcha_Notes_5748214695198720 (Read-only file system)
```

I think that's because live App Engine doesn't have a hard drive. To fix this, I think we can go directly from docx4j to Blobstore. Basically I'm stealing this idea from here: https://stackoverflow.com/questions/13360867/save-wordprocessingmlpackage-to-bytearrayinputstream (see the third answer, the one that starts with "Since 3.1.0..."

Here's the documentation for the version of dcx4j we're using: https://javadoc.io/static/org.docx4j/docx4j/6.1.2/index.html?org/docx4j/openpackaging/packages/WordprocessingMLPackage.html

Do a ctrl+f for "save" in there. I think you want the one that takes an OutputStream, or maybe the one that takes an OutputStream and some flags. That will allow you to pass in something like a ByteArrayOutputStream which you can then pass into the storage.create() function that's inside uploadObject() in the Session class.

Let me know if that makes sense. I'll be around the rest of the night if you have questions. I know this is some extra surprise work, so let me know if you want me to try to make a PR or something!

If we can get the live version working, I think it would be cool to give out the url during the demo to have folks try it out!

### PR DESCRIPTION
**Pull request by verdantpeas**
### Changes
 - Modify `writeConvertedDoc()` to write to `OutputStream` instead of a `File` in local directory 
- Resolves #26

### Additional Information 
- Deployed and tested live version: https://summer20-sps-33.uc.r.appspot.com/

image
image

### CODE REVIEW

File: src/main/java/com/google/sps/data/Note.java [hunk 1]
```diff
@@ -107,18 +108,16 @@ public String getFileName(){
...
     //if no categories classified then the title is "Getcha Notes" by default
     String title = !categories.isEmpty() ? categories.get(0) : "Getcha Notes";
 
     WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.createPackage();
     wordMLPackage.getMainDocumentPart().addStyledParagraphOfText("Title", title);
     wordMLPackage.getMainDocumentPart().addParagraphOfText(message);
 
-    // saved in Team-33-Note-App/target/portfolio-1
     fileName = String.format("Getcha_Notes_%d", sessionKey.getId());
-    filePath = String.format("%s/%s", System.getProperty("user.dir"), fileName);
```
Comment (KevinWorkman) [inline src/main/java/com/google/sps/data/Note.java:120]: I think you might be able to get rid of the `fileName` and `filePath` variables now? Are they used anywhere?

File: src/main/java/com/google/sps/servlets/FormHandlerServlet.java [hunk 2]
```diff
@@ -103,15 +104,17 @@ public void doPost(HttpServletRequest request, HttpServletResponse response) thr
     noteEntity.setProperty("categories", note.classifyText());
     noteEntity.setProperty("timestamp", timestamp);
 
+    OutputStream outStream = new ByteArrayOutputStream();
     try {
-      note.writeConvertedDoc();
+      note.writeConvertedDoc(outStream);
     } catch (Docx4JException e) {
       System.out.println(e);
```
Comment (KevinWorkman) [inline src/main/java/com/google/sps/servlets/FormHandlerServlet.java]: While you're here, maybe change this to `e.printStackTrace()` to make future debugging easier?

**Comment by verdantpeas** [comment]
Thanks for all the help with debugging @KevinWorkman

File: src/main/java/com/google/sps/servlets/FormHandlerServlet.java [hunk 3]
```diff
@@ -103,15 +104,17 @@ public void doPost(HttpServletRequest request, HttpServletResponse response) thr
...
     }
 
     Session session = new Session();
     String objectName = note.getFileName() + ".docx";
-    session.uploadObject(objectName, note.getFilePath());
+    
+    session.uploadObject(objectName, ((ByteArrayOutputStream)(outStream)).toByteArray());
```
Comment (KevinWorkman) [inline src/main/java/com/google/sps/servlets/FormHandlerServlet.java:117]: Just out of curiosity, if two users upload two files with the same name, will the new file overwrite the old one? Or does Cloud Storage give you a unique url for each upload?

**Review by KevinWorkman — APPROVED** [review]
This looks great, thank you for putting this together so quckly!

File: src/main/java/com/google/sps/servlets/FormHandlerServlet.java (hunk 3 above)
Comment (verdantpeas) [reply src/main/java/com/google/sps/servlets/FormHandlerServlet.java:117]: I believe Cloud Storage gives a unique URL for each object. However, in our case, files shouldn’t have the same names since the file name is based on the unique session id

Comment (joshflchan) [reply src/main/java/com/google/sps/servlets/FormHandlerServlet.java:117]: I believe Cloud Storage gives a unique URL for each object. However, in our case, files shouldn’t have the same names since the file name is based on the unique session id

File: src/main/java/com/google/sps/data/Note.java (hunk 1 above)
Comment (verdantpeas) [reply src/main/java/com/google/sps/data/Note.java:120]: `fileName` is still used to assign a unique file name for the Note object based on the session ID

**Review by oulily — APPROVED** [review]
